### ISSUE TITLE
OwlProgram loads always the FaustTest patch

### ISSUE THREAD

**Issue by roelkers** [pingdynasty/OwlProgram#116]
Hello,

I'm trying out the offline upload method for Owl (Lich) for the Faust programming language. My patches are compiling and are uploaded successfully.
However, the resulting patch running on the Owl always seem to be the "FaustTest" program with one button to trigger the test tone. Could it be some caching issue ? i removed everything else from the PatchSource folder.
With C++ patches this issue is not happening for me.The online upload using RebelTech works fine also, but it uses an older version of Faust which is why i wanted to try the offline road. Could it be that the version of faust running locally is too current? 

To compile my patch i use:
```make clean```

```
$ SLOT=3 FAUST=EnsembleOwl make store                             
$ Building patch EnsembleOwl
Sending patch EnsembleOwl to OWL-* to store in slot 3
JUCE v5.2.1
```

**Comment by antisvin** [comment]
Very strange. FaustTest is what is used in some cases, like when you run `make check`. Did you run that command before?

Also, are you using the `develop` branch to build patches? Under which OS do you get this issue? Does the same thing happen if you run `make load` instead of `make store`?

I would suggest confirming that you have no data in Build directory after running `make clean`. You could safely delete that directory manually too.

**Comment by roelkers** [comment]
Did not run `make check` before, however `make load` ended up working actually so I could play the patch inside the memory of the module. Storing still gives this Test example patch though, also after clearing the build folder etc.

Maybe I'll try doing a firmware update/reset and see if that helps.

**Comment by antisvin** [comment]
BTW, which firmware version are you currently running? I think that before messing with firmware you could try erasing patch storage and writing patch again, i.e. it can be done from here - https://www.rebeltech.org/patch-library/device

**Comment by roelkers** [comment]
Hello, thanks for all the suggestions. The issue was fixed after resetting the storage.
