### ISSUE TITLE
Settle on a uniformed way of representing frequency for filters and oscillators

### ISSUE THREAD

**Issue by giuliomoro** [pingdynasty/OwlProgram#49]
either normalized or hertz. And/or add ways of converting between the two.

**Comment by pingdynasty** [comment]
Applies to all sample rate dependent parameters:
- oscillator frequency
- filter cutoff
- envelope times
- parameter smoothing

At the moment many classes require the sample rate to be set either in the constructor or by calling a setter. Both complicate object initialisation. RIIA ensures that the value gets set, but makes it difficult e.g. to define arrays of oscillators.

Setting parameters as a percentage of Nyquist frequency (ie normalised) can be convenient and efficient, but is perhaps less intuitive than recognisable frequencies in Hertz.

At the moment we have e.g. `BiquadFilter::setLowpass(fc, q)` which expects a normalised `fc` parameter, and `Oscillator::setFrequency(f)` which expects Hertz.

Possible solutions:
1. add `Oscillator::setRate(n)` which takes normalised value
2. revise Biquad to take Hertz cutoff frequency
3. define a global `getSampleRate()` available to library classes so that SR does not have to be passed in the constructor.
4. provide a class with static conversion methods: `float Frequency::normal(hz, SR)`, `float Frequency::hertz(normal, SR)`
5. provide static conversion methods in all classes that require it (through inheritance)

3) is problematic because the object may not be required to run at sample rate. E.g. an envelope or LFO could run at block rate, `getSampleRate()/getBlocksize()`. Could still be useful to provide a default value.

**Comment by giuliomoro** [comment]
Each of Envelope, Oscillator, Biquad will take an optional constructor parameter "timebase", which is the interval  (in samples) at which output will be requested by the user during the process. Effectively this re-scales any frequency or duration parameters passed in.

**Comment by giuliomoro** [comment]
The above was done for Envelope and Oscillator in 4e496b9. Biquad postponed

**Comment by pingdynasty** [comment]
done
