### ISSUE TITLE
DBAP algorithm

### ISSUE THREAD

**Issue by pingdynasty** [pingdynasty/OwlProgram#58]
Distance Based Amplitude Panning

We need an OWL patch to control a VCA Matrix with 4 ins (sound sources) and 4 outs (speakers).
The patch should allow the virtual positioning of each sound source on the plane, and compute amplitude levels for each input at each speaker, ie the level for each of the 16 VCAs in the matrix.
This will work with a CV Expander with 16 outputs, connected to the CV inputs of an analogue VCA matrix which will handle the audio signal path.

The assumptions are that the speakers are in each corner of a square room, and that the sources are all located within the room boundaries. Nice to haves, in order of importance:
- diffusion / spread
- slew rate
- sources outside speaker boundaries
- positionable speakers

The control parameters should be, for polar coordinates:
- A select sound source, seven values: 1, 2, 3, 4, 1+2, 3+4, or all at once
- B angle 0-360 degrees
- C distance from centre
- D diffusion / spread

Alternative with Cartesian coordinates:
- A source
- B X
- C Y
- D diffusion / spread

An additional E parameter could control slew rate, to slow down CV output changes, to be implemented with `SmoothValue`.

The levels should be set with `setParameterValue(id, value)`. Input 1 levels on speakers 1, 2, 3, 4 should be sent to parameters `AA`, `AB`, `AC`, `AD`. Input 2 `AE` to `AH`, input 3 `BA` to `BD` et c.

ref:
http://jamoma.org/publications/attachments/icmc2009-dbap-rev1.pdf
https://github.com/kronihias/dbap

**Comment by pingdynasty** [comment]
To clarify, parameters B, C, D are set per sound source, and A selects which source/s are currently being controlled.

**Comment by giuliomoro** [comment]
What happens when A is switched to control another source? At which point will the pots B,C,D be effective? After they are moved "a bit" from their initial position or when they reach the value currently set for that source? Is there already something like this in the core or do you want to spec out a Class for this?

**Comment by pingdynasty** [comment]
Good question, and it applies to multiplexing parameters in general. Strategies that can be implemented are skip-to, pick-up, or relative.
Let's do the easiest: when a source is selected the parameters immediately skip to whatever value the pots are currently on.
And let's create another issue for the other methods.

**Comment by giuliomoro** [comment]
I think that it could be implemented in the class that currently takes care of parameter smoothing, adding an additional parameter to it "multiplexing"

**Comment by giuliomoro** [comment]
what's the slew rate here?

**Comment by pingdynasty** [comment]
Slew rate applies to the output values, ie the 16 VCA levels. By smoothing them we get softer transitions and can effectively slow down all movements. It also alleviates some of the need for clever parameter multiplexing if we can skip from A to C without moving B very much.
Therefore the best way to implement this I think is the simplest way: don't store a target value, instead simply use a SmoothValue for each output parameter and only update the value when the corresponding source is selected.

**Comment by giuliomoro** [comment]
Drafted Dbap class.

Compile the test with this:

```
g++ testDbap.cpp LibSource/Dbap.hpp LibSource/FloatArray.cpp -std=c++11 -lm && ./a.out
```

here is the output, see if it makes sense

```
With 4 speakers in:
[0]: 1.000 1.000
[1]: -1.000 1.000
[2]: -1.000 -1.000
[3]: 1.000 -1.000


==============spread: 0.000=====

For source in 0.990, 0.990, gains:
0.007    1.000

0.005    0.007

For source in 1.000, 0.000, gains:
0.289    0.645

0.289    0.645

For source in -1.000, -0.900, gains:
0.053    0.037

0.997    0.050

For source in -1.000, 1.000, gains:
nan    0.000

0.000    0.000



==============spread: 0.500=====

For source in 0.990, 0.990, gains:
0.228    0.932

0.164    0.228

For source in 1.000, 0.000, gains:
0.311    0.635

0.311    0.635

For source in -1.000, -0.900, gains:
0.242    0.170

0.927    0.230

For source in -1.000, 1.000, gains:
0.933    0.227

0.227    0.163



==============spread: 1.000=====

For source in 0.990, 0.990, gains:
0.365    0.812

0.273    0.365

For source in 1.000, 0.000, gains:
0.354    0.612

0.354    0.612

For source in -1.000, -0.900, gains:
0.378    0.277

0.806    0.363

For source in -1.000, 1.000, gains:
0.813    0.364

0.364    0.272



==============spread: 1.500=====

For source in 0.990, 0.990, gains:
0.432    0.716

0.338    0.432

For source in 1.000, 0.000, gains:
0.394    0.587

0.394    0.587

For source in -1.000, -0.900, gains:
0.442    0.341

0.711    0.428

For source in -1.000, 1.000, gains:
0.717    0.431

0.431    0.337
```

**Comment by pingdynasty** [comment]
How do we avoid NaN results (spread=0, source in -1.0 1.0)?
Do we need to keep pos > -1.0, pos < 1.0 and/or spread > 0.0?

**Comment by giuliomoro** [comment]
they are there "by design" when spread is 0 and the source is in the same place as the speaker.

**Comment by pingdynasty** [comment]
But the output value needs to be 1.0, right? NaN doesn't convert to a CV...

Code looks good. Instead of commenting out includes in FloatArray.cpp you can define the header guard in your test file (`#define __MESSAGE_H`)  along with the overrides (ASSERT, min), before #including the .cpp file directly.
Or how about making a test patch?

Allocation and initialisation should be done in a `static Dbap* Dbap::create(int sources, ...)` method, and deallocation in `destroy()`. The constructor should take pointers to pre-allocated resources.

**Comment by giuliomoro** [comment]
Updated the code.

I have troubles compiling proper test patches (`make test TEST=TestPatchName`), it seems broken, as reported elsewhere.

The `Dbap` class should store:
- the array of sources
- the speaker positions
- should it store an array of gains as well?
- do you want to write the prototype for `Dbap::create` and `DbapSource::create`?

Any methods you see missing? Do you want all the getters as well as the setters? Should you be able to retrieve the `sources` array from a `Dbap` object and interact with them directly? Otherwise all the set/get methods in `DbapSource` should have the corresponding method in `Dbap`

Example patch:
https://github.com/giuliomoro/gmOwlPatches/blob/master/DbapExamplePatch.hpp

No smoothing at the moment. Not sure one smoothing per block is going to be enough to avoid zipper noise, given that we are directly modulating the amplitude, unless you want the smooth to be ve-ery smooth.

Maybe it is better to use ramps instead? (though it wouldn't prevent the problem with the multiplexing. This could be addressed by either using the pushbutton when you want to change the source you are controlling or by waiting half a second after you select a source before you start controlling it).

**Comment by pingdynasty** [comment]
Trouble with test patches: I've looked at #45 and #54 but not sure what the problem is. Running tests on Mac, with a specific compiler, or smth more general?

**Comment by pingdynasty** [comment]
I've committed some changes (4cabac3), mostly to initialisation.

**Comment by giuliomoro** [comment]
Ok, I left some comments on your code there, did you get notified?

**Comment by pingdynasty** [comment]
done as patch
